Fix tests for Python3.11
Apparently, PonyORM does not support Python version 3.11 properly yet.
In case of some generator-involving expressions, such as:
orm.count(row.id for row in cache.Cache); there appears the following:
pony.orm.decompiling.DecompileError: Unsupported operation: RETURN_GENERATOR
however using construction cache.Cache.select().count() works fine.

Ref: https://github.com/ponyorm/pony/issues/668